In [1]:
import cv2
import os
import random
import numpy as np 
import matplotlib.pyplot as plt 

# img = cv2.imread("img/test.jpg")
# img = cv2.resize(img,(625,810))
# plt.imshow(img)
# print(img.shape)


In [3]:
dir = r"img"
catagories = ['bbox','fbox']

In [21]:
data = list()
for catagory in catagories:
  folder = os.path.join(dir,catagory)
  print(folder)
  label = catagories.index(catagory)

  for img in os.listdir(folder):
    img = os.path.join(folder,img)
    #print(img)
    img_arr = cv2.imread(img)
    img_arr = cv2.resize(img_arr,(60,25))
    data.append([img_arr,label])


img/bbox
img/fbox


In [22]:
random.shuffle(data)


In [24]:
x = list()
y = list()
for features,label in data:
  x.append(features)
  y.append(label)

print(y)

[0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1]


In [25]:
x = np.array(x)
y = np.array(y)
print(x)

[[[[254 254 254]
   [255 255 255]
   [254 254 254]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [254 254 254]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [254 254 254]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [254 254 254]
   ...
   [254 254 254]
   [254 254 254]
   [254 254 254]]

  [[255 255 255]
   [255 255 255]
   [254 254 254]
   ...
   [254 254 254]
   [255 255 255]
   [254 254 254]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[129 177 159]
   [131 179 161]
   [134 182 164]
   ...
   [142 184 166]
   [140 182 164]
   [139 181 163]]

  [[129 177 159]
   [130 178 160]
   [132 180 162]
   ...
   [141 183 165]
   [141 183 165]
   [140 182 164]]

  [[133 181 163]
   [132 180 162]
   [134 182 164]
   ...
   [145 187 169]
   [142 184 167]
   [140 182

In [ ]:
x = x/255
#print(x)

In [26]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Activation

In [39]:
model = Sequential()
model.add(Conv2D(30,(3,3),input_shape=x.shape[1:],activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(30,(3,3),input_shape=x.shape[1:],activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(2,activation='softmax'))


In [40]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [41]:
model.fit(x,y,epochs=15,validation_split=0.1)

Epoch 1/15
8/8 [==============================] - 1s 70ms/step - loss: 9.3043 - accuracy: 0.5598 - val_loss: 7.6056 - val_accuracy: 0.5000
Epoch 2/15
8/8 [==============================] - 0s 54ms/step - loss: 2.3931 - accuracy: 0.6966 - val_loss: 1.9321 - val_accuracy: 0.6923
Epoch 3/15
8/8 [==============================] - 0s 50ms/step - loss: 2.4690 - accuracy: 0.6667 - val_loss: 2.6837 - val_accuracy: 0.6538
Epoch 4/15
8/8 [==============================] - 0s 52ms/step - loss: 1.4773 - accuracy: 0.7479 - val_loss: 1.0320 - val_accuracy: 0.7692
Epoch 5/15
8/8 [==============================] - 0s 50ms/step - loss: 1.0274 - accuracy: 0.8162 - val_loss: 0.9014 - val_accuracy: 0.9231
Epoch 6/15
8/8 [==============================] - 0s 48ms/step - loss: 0.6409 - accuracy: 0.8761 - val_loss: 0.9575 - val_accuracy: 0.8846
Epoch 7/15
8/8 [==============================] - 0s 49ms/step - loss: 0.5913 - accuracy: 0.8675 - val_loss: 0.9286 - val_accuracy: 0.8462
Epoch 8/15
8/8 [===========

In [42]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 23, 58, 30)        840       
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 11, 29, 30)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 9, 27, 30)         8130      
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 4, 13, 30)        0         
 2D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 1560)              0         
                                                                 
 dense_2 (Dense)             (None, 2)                

In [55]:
from keras.preprocessing import image
import numpy as np
c = 0
for i in range(5):
  for j in range(4):
    st = '2ci '+str(i)+' '+str(j)+'.jpg'
    print('reading :',st)
    img_pred = cv2.imread(r"img/test/"+st)
    img_pred = cv2.resize(img_pred,(60,25))
    img_pred = np.expand_dims(img_pred,axis=0)
    img_pred = np.array(img_pred)
    res = model.predict(img_pred)
    print(res)

    if res[0][0] > res[0][1]:
      print('Filled')
    else:
      print('Blanked')

reading : 2ci 0 0.jpg
1/1 [==============================] - 0s 20ms/step
[[7.321319e-06 9.999927e-01]]
Filled
reading : 2ci 0 1.jpg
1/1 [==============================] - 0s 33ms/step
[[4.3291777e-07 9.9999952e-01]]
Filled
reading : 2ci 0 2.jpg
1/1 [==============================] - 0s 21ms/step
[[4.8150848e-09 1.0000000e+00]]
Filled
reading : 2ci 0 3.jpg
1/1 [==============================] - 0s 20ms/step
[[2.0872490e-05 9.9997914e-01]]
Filled
reading : 2ci 1 0.jpg
1/1 [==============================] - 0s 21ms/step
[[1.6175235e-04 9.9983823e-01]]
Filled
reading : 2ci 1 1.jpg
1/1 [==============================] - 0s 25ms/step
[[1.6360003e-05 9.9998367e-01]]
Filled
reading : 2ci 1 2.jpg
1/1 [==============================] - 0s 22ms/step
[[6.241526e-06 9.999938e-01]]
Filled
reading : 2ci 1 3.jpg
1/1 [==============================] - 0s 22ms/step
[[1.3065775e-04 9.9986935e-01]]
Filled
reading : 2ci 2 0.jpg
1/1 [==============================] - 0s 31ms/step
[[6.4942396e-05 9.9993503e

In [62]:
from keras.preprocessing import image
import numpy as np
st = '1ci 0 3.jpg'
print('reading :',st)
img_pred = cv2.imread(r"img/test/"+st)
img_pred = cv2.resize(img_pred,(60,25))
img_pred = np.expand_dims(img_pred,axis=0)
img_pred = np.array(img_pred)
res = model.predict(img_pred)
print(res)

if res[0][0] > res[0][1]:
  print('Filled')
else:
  print('Blanked')

reading : 1ci 0 3.jpg
1/1 [==============================] - 0s 21ms/step
[[9.9995506e-01 4.4911369e-05]]
Filled
