#Training the model

In [21]:
import cv2
import os
import random
import numpy as np 
import matplotlib.pyplot as plt 

dir = r"img"
catagories = ['bbox','fbox']

data = list()
for catagory in catagories:
  folder = os.path.join(dir,catagory)
  print(folder)
  label = catagories.index(catagory)

  for img in os.listdir(folder):
    img = os.path.join(folder,img)
    #print(img)
    img_arr = cv2.imread(img)
    img_arr = cv2.resize(img_arr,(60,25))
    data.append([img_arr,label])

  random.shuffle(data)

  x = list()
y = list()
for features,label in data:
  x.append(features)
  y.append(label)

x = np.array(x)
y = np.array(y)


import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,Activation

model = Sequential()
model.add(Conv2D(30,(3,3),input_shape=x.shape[1:],activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(30,(3,3),input_shape=x.shape[1:],activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(2,activation='softmax'))


model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x,y,epochs=15,validation_split=0.1)


img/bbox
img/fbox
Epoch 1/15
8/8 [==============================] - 1s 83ms/step - loss: 18.5865 - accuracy: 0.4915 - val_loss: 9.1006 - val_accuracy: 0.4231
Epoch 2/15
8/8 [==============================] - 0s 58ms/step - loss: 4.8525 - accuracy: 0.5000 - val_loss: 1.9841 - val_accuracy: 0.5769
Epoch 3/15
8/8 [==============================] - 0s 56ms/step - loss: 1.8143 - accuracy: 0.6880 - val_loss: 1.6074 - val_accuracy: 0.5385
Epoch 4/15
8/8 [==============================] - 0s 57ms/step - loss: 1.2750 - accuracy: 0.7607 - val_loss: 0.7202 - val_accuracy: 0.7308
Epoch 5/15
8/8 [==============================] - 0s 58ms/step - loss: 0.7423 - accuracy: 0.8718 - val_loss: 0.5989 - val_accuracy: 0.6538
Epoch 6/15
8/8 [==============================] - 0s 56ms/step - loss: 0.4847 - accuracy: 0.8675 - val_loss: 0.3728 - val_accuracy: 0.8462
Epoch 7/15
8/8 [==============================] - 0s 56ms/step - loss: 0.4268 - accuracy: 0.8718 - val_loss: 0.5546 - val_accuracy: 0.8077
Epoch 8/

#Preprossing image


In [22]:
img = cv2.imread("img/test3.jpg")
img = cv2.resize(img,(625,810))
#print(img.shape)

data = list()
ini = 90-10
#crop_img = img[100:125,30:62]
#plt.imshow(crop_img)

for i in range(5):
    for j in range(4):
        crop_img = img[ini:ini+25,20:80]
        ini = ini+22
        pt = 'img/test/ci '+str(i)+' '+str(j)+'.jpg'
        cv2.imwrite(pt, crop_img)
        print('success : ',pt)
    ini = ini + 20

success :  img/test/ci 0 0.jpg
success :  img/test/ci 0 1.jpg
success :  img/test/ci 0 2.jpg
success :  img/test/ci 0 3.jpg
success :  img/test/ci 1 0.jpg
success :  img/test/ci 1 1.jpg
success :  img/test/ci 1 2.jpg
success :  img/test/ci 1 3.jpg
success :  img/test/ci 2 0.jpg
success :  img/test/ci 2 1.jpg
success :  img/test/ci 2 2.jpg
success :  img/test/ci 2 3.jpg
success :  img/test/ci 3 0.jpg
success :  img/test/ci 3 1.jpg
success :  img/test/ci 3 2.jpg
success :  img/test/ci 3 3.jpg
success :  img/test/ci 4 0.jpg
success :  img/test/ci 4 1.jpg
success :  img/test/ci 4 2.jpg
success :  img/test/ci 4 3.jpg


#Testing the data using Trained Model

In [23]:
for i in range(5):
  for j in range(4):
    st = 'ci '+str(i)+' '+str(j)+'.jpg'
    print('reading :',st)
    img_pred = cv2.imread(r"img/test/"+st)
    img_pred = cv2.resize(img_pred,(60,25))
    img_pred = np.expand_dims(img_pred,axis=0)
    img_pred = np.array(img_pred)
    res = model.predict(img_pred)
    print(res)

    if res[0][0] > res[0][1]:
      print('Filled')
    else:
      print('Blanked')

reading : ci 0 0.jpg
1/1 [==============================] - 0s 78ms/step
[[0.22991323 0.7700868 ]]
Blanked
reading : ci 0 1.jpg
1/1 [==============================] - 0s 24ms/step
[[0.00848683 0.9915132 ]]
Blanked
reading : ci 0 2.jpg
1/1 [==============================] - 0s 24ms/step
[[0.01356666 0.98643327]]
Blanked
reading : ci 0 3.jpg
1/1 [==============================] - 0s 21ms/step
[[0.00477195 0.99522805]]
Blanked
reading : ci 1 0.jpg
1/1 [==============================] - 0s 23ms/step
[[0.03846125 0.96153873]]
Blanked
reading : ci 1 1.jpg
1/1 [==============================] - 0s 20ms/step
[[0.0528212  0.94717884]]
Blanked
reading : ci 1 2.jpg
1/1 [==============================] - 0s 21ms/step
[[0.0086407  0.99135935]]
Blanked
reading : ci 1 3.jpg
1/1 [==============================] - 0s 21ms/step
[[0.00363291 0.9963671 ]]
Blanked
reading : ci 2 0.jpg
1/1 [==============================] - 0s 29ms/step
[[0.00777308 0.99222696]]
Blanked
reading : ci 2 1.jpg
1/1 [===========